[Cloud] Commands APIs
drogue-iot/rfcs pull request #2
Opened 2021-02-01 14:13 UTC by dejanb

2021-02-15 09:53 UTC, ctron commented on active/0002-commands-apis.md
> +* `POST /command{/<custom>}?tenant=<tenant>&device=<device>&command=<command>`
We use `app` now :grin: … But I guess we still have "tenant" all over the place for a bit.

2021-02-15 09:55 UTC, ctron commented on active/0002-commands-apis.md
> +  * Headers:
I think it would be great to have a dedicated status code for "message received" vs "message received with returned command".

2021-02-15 09:56 UTC, ctron commented on active/0002-commands-apis.md
> +* `POST /command/outbox{/<custom>}?tenant=<tenant>&device=<device>&request=<request>&status=<status>`
That may conflict with the above "/command/{/custom}" pattern. I had the same issue and I am not sure anymore if allowing the arbitrary suffix is such a good idea in our default case.

2021-02-15 09:57 UTC, ctron commented
I like the proposal! Especially the way for a device to "check its inbox".

I think we should also have some way to deal with gateways and devices behind a gateway.

2021-02-16 07:35 UTC, lulf requested changes
No other comments from me than.... awesome!

+1 on replacing tenant with application or app

Good idea with the inbox vs outbox concept, its easy to understand.

2021-02-17 15:49 UTC, jbtrystram commented on active/0002-commands-apis.md
> +    * Timeout: Wait for commands for specified amount of time in seconds.
maybe renaming the time to wait command parameter to `command_timeout` or something more explicit ? 
I am thinking on the perspective of someone reading this for the publish documentation (it's a data publish operation after all) and getting confused.

2021-02-17 15:52 UTC, jbtrystram commented
> Good idea with the inbox vs outbox concept, its easy to understand.

Indeed, great idea !

2021-02-22 13:53 UTC, dejanb commented on active/0002-commands-apis.md
> +* `POST /command/outbox{/<custom>}?tenant=<tenant>&device=<device>&request=<request>&status=<status>`
I agree, especially as we adopted heavy use of parameters. I would say let's add all the customisation through additional parameters if needed

2021-02-22 14:27 UTC, dejanb commented on active/0002-commands-apis.md
> +    * Timeout: Wait for commands for specified amount of time in seconds.
In the current implementation it's called `ttd` (time-til-disconnect), similar to what we have in Hono. I was thinking to unify it to `timeout` to be consistent throughout the API.

2021-02-23 12:01 UTC, merged